import { createRoot } from 'react-dom/client'
import App from './App'
import './styles/global.css'
import './styles/dashboard.css'
import './styles/profile.css'
import './styles/login.css'
import './styles/settings.css'
import './styles/security.css'
import './styles/contact.css'
import './styles/notifications.css'
import './styles/notification-drawer.css'
import './styles/bookings.css'
import './styles/header-overrides.css'
import './styles/closure.css'
import './styles/slots.css'
import './styles/slots-grid-view.css'
import './styles/slot-details.css'
import './styles/add-slot-dialog.css'
import './styles/manage-slots-table.css'
import './styles/bulk-slots.css'
import './styles/availability.css'
import './styles/analytics.css'

createRoot(document.getElementById('root')!).render(<App />)
